language: java
jdk:
- oraclejdk8
before_install:
- chmod +x ./gradlew
- curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar
  >jpm4j.jar
- java -jar jpm4j.jar -u init
- "~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly"
after_success:
- "~/jpm/bin/codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml"
deploy:
  - provider: releases
    api_key:
      secure: ltLzm1VWcBj5sLTqtEUQyd3JG5pYZ6nQG5czsWB28hvJ3wkVa6vt7L5j3OS8wZuaIdE6eDJ2rMfQ5qS1FAE91SiQfCsMArsZ5C2cWm7BSz70MAa2zCWgxxlMsvARTnSLaP9mVgbZN0js2p0ETVVuUj+MG1dQJGXhsggmFI3ZSxCnWpoAhtGDVvQr8BZp4w5hPJ0Xm144v9ZnT2oUwmwevlVFzO+QzjiUJwPCjy4y6rJAJDdYdY0mTUQq7Y9SwkjXQACNwDRs6ITQ4nbClCk7RtDIKUFYWvuq9IRD0OhVXibTtMC4yocl+PsM6XvCYCAWPjLon20Pc2fdepzWhYPkyoOf9SDDUFAHEjYQ+vw2BkQpx3WwMZDLJbGXI1z0+evYUhSxr7oRSzoRfpCYFtEJ7toLb8SPTsYkyQQp5N1EDNtnIgBZhsQpFdxDgZ8vrVeWiLVtzX5ARgz0GV/yL2v+2ZzPg7usEJSNC6xwyjGiPGDtggUy2HIsP1ohl56VVvU5RjfoKcXxysbm0L43sddZHIuNggyku7pNlYsgHdrUf/0qanxxrU46w8M4vUdyd1oC/pXwaUkpdjA6nFU+ouoX1ScihxZzlkE2TYEFJqbKcWQ8d9zeYW90pemc8oWZJcylyF0ef2MJKy3DgNplnoSJM6q6sDunAA5wGN5A+vu/Ahw=
    skip_cleanup: true
    file: build/libs/*.jar
    on:
      repo: Sybit-Education/airtable.java
      tags: true
  - provider: script
    skip_cleanup: true
    script: gradlew bintrayUpload
    on:
      tags: true